### ISSUE TITLE
Hw1

### ISSUE THREAD

**Issue by Komineq** [korona-science/homework-Komineq#1]
Kod w odpalany w vs code jupyter notebook, działa i zwraca poprawne wyniki, ale commit nie przechodzi.

**Comment by Torisels** [comment]
Linijka 4 w pliku hw.1 `imoprt datetime`. Powinno być `import`

**Comment by Komineq** [comment]
Poprawiłem na import, ale nadal coś jest nie tak.

**Comment by Torisels** [comment]
Uzywasz zmiennych `mies` i `dzien` wewnatrz funkcji. Deklaracja funkcji ma `day` oraz `month`. Musisz zrobic tak, by były takie same.

**Comment by Komineq** [comment]
Ok po commicie teraz już zwraca co jest źle

**Comment by Komineq** [comment]
Czym może być tak że nie przechodzi testu, bo dodatkowo oprócz kolejności państw zwraca też ilość zarażonych?

**Comment by Komineq** [comment]
Ok, tak było rzeczywiście. Dziękuję za pomoc
