### ISSUE TITLE
Hw_2 Task 2

### ISSUE THREAD

**Issue by Komineq** [korona-science/homework-Komineq#2]
Mam problem z drugim zadaniem z drugiej pracy domowej, z jakiegos powodu wszystkie testy nie przechodzą, chociaż w teorii powinno być dobrze. Sprawdziłem przykładowe wyniki w vs code
![Capture](https://user-images.githubusercontent.com/62251988/77254460-60ce9400-6c61-11ea-8579-474396c9cc05.PNG)

**Comment by Torisels** [comment]
Sprobuj dodac w drugim `.tolist()`

**Comment by Komineq** [comment]
Super, poszło :)
Bardzo dziękuję.
